### ISSUE TITLE
Logout link doesn't work in Django 5.x

### ISSUE THREAD

**Issue by bachvtuan** [kajala/django-j2fa#1]
![image](https://github.com/user-attachments/assets/fb13ba23-242a-42fa-8396-39bfc8bb6c25)

![image](https://github.com/user-attachments/assets/fd33ce3b-99ea-4a77-93a2-85c5efa468ec)

The logout link via POST is supported since Django 4.x so we don't have incompatible issue from lower Django version.

Current template:

```html
<a href="{% url 'admin:logout' %}">{% trans 'Logout' %}</a>
```

Suggest template:

```html
  <form id="logout-form" method="post" action="{% url 'admin:logout' %}" style="display: inline-block;" >
      {% csrf_token %}
      <button class="btn btn-link" type="submit">{% translate "Logout" %}</button>
  </form>
```

**Comment by kajala** [comment]
fixed in 3.8.11
